name: Auto Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: List files
      run: dir /s

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./releases/v${{ steps.get_version.outputs.VERSION }}/AutoExportTool_Pro_V${{ steps.get_version.outputs.VERSION }}.ms
        asset_name: AutoExportTool_Pro_V${{ steps.get_version.outputs.VERSION }}.ms
        asset_content_type: application/octet-stream

    - name: Upload release notes
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./releases/v${{ steps.get_version.outputs.VERSION }}/release_notes_v${{ steps.get_version.outputs.VERSION }}.txt
        asset_name: release_notes_v${{ steps.get_version.outputs.VERSION }}.txt
        asset_content_type: text/plain